name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  CodeFormattingCheck:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/mint
    steps:
      - uses: actions/checkout@v2
    #   - name: Check for homebrew updates
    #     run: brew update
      - name: Cache Mint packages
        uses: actions/cache@v1
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - name: Install Mint
        run: |
          brew upgrade mint || brew install mint || true
      - name: Install swiftformat via mint
        run: |
          mint bootstrap
      - name: Format Swift code
        run: mint run swiftformat --verbose .
      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD
