name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run code coverage
      run: |
#gem install slather
        swift package generate-xcodeproj
        xcodebuild -enableCodeCoverage YES -project swift-package-os-example.xcodeproj -scheme swift-package-os-example-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build test
#slather
    # xcrun llvm-cov export -format="lcov" .build/debug/swift-package-os-examplePackageTests.xctest/Contents/MacOS/$swift-package-os-examplePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Update Code Coverage
      run: bash <(curl https://codecov.io/bash) -d -f Tests/cobertura.xml
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
