name: TestApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        cd TestApp
        xcodebuild -scheme TestApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build test
